require "rhythm.plugins"
require "rhythm.options"
require "rhythm.keymaps"
require "rhythm.cmp"
require "rhythm.lsp"
require "rhythm.telescope"
require "rhythm.treesitter"
require "rhythm.leap"
require "rhythm.gitsigns"
require "rhythm.tagbar"
require "rhythm.nvim-tree"
require "rhythm.autocmds"
require "rhythm.zen-mode"
require "rhythm.twilight"
require "rhythm.nvim-notify"

